spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      path: /sql
      settings.trace: false
      settings.web-allow-others: false

server:
  port: 6140
  context-path: rest

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    filter: true
    tagsSorter: alpha
    docExpansion: 'none'